services:
  - type: web
    name: pldg-atp-rankings
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: RENDER
        value: true
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src
      sizeGB: 1 