services:
  - type: web
    name: pldg-atp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false 